### ISSUE TITLE
BUG: variable with variant that have engine singleton assigned will obfuscate

### ISSUE THREAD

**Issue by normano** [cherriesandmochi/gdmaim#5] opened 2024-01-30 00:43 UTC
Had a bug right under our noses. If you look at haptics addon in the experiment repo you'll see that the function called on the singleton is obfuscated, but should not be. The variable itself is declared variant, so anything referenced on it should be left alone since there's not much information on the variant to do any obfuscation.

This is easily mitigated by using the obfuscate false on these kinds of scripts which are typically addons.

The one that is not mitigated by ##obfuscate false is when singleton.init() is called from an addon. I demonstrate this in the window.gd code.

**Comment by cherriesandmochi** [comment] 2024-01-30 09:44
Not sure if I'm misunderstanding something, but singletons and consequentially calls to it, are supposed to get obfuscated.
`##OBFUSCATE false` only works on _declarations_ being made, which is by design as completely stopping snippets from getting obfuscated, without resolving any global symbols, will usually break any code.
It might make sense to rename the hint to something like `##OBFUSCATE_SYMBOL`, to make it clearer what it actually does.

**Comment by cherriesandmochi** [comment] 2024-01-31 09:48
I did not think about external plugins at all. Okay, that's going to be a bit tricky. 

The only automated way I can think of is to somehow try to load the dynamic libraries during export and then using `ClassDB` to fetch all methods and properties. But alas, I'm not quite sure if that's possible.
Alternatively, it might actually be possible to launch a fake instance of Godot using all target dynamic libraries, which could then report back with all methods and properties gathered.

Not sure yet, how feasible both of those approaches are, the first one is probably not possible in the first place.
For now, the 'best' workaround is manually stopping all the plugin methods and properties I guess. Something like:
```
##OBFUSCATE false
var plugin_property
func init(): pass
func plugin_method(): pass
func another_plugin_method(): pass
##OBFUSCATE true
```

Ah okay, well if `init` is a commonly used plugin method, I could make an exception and add it to the built-ins, at least until I have figured out how to deal with external plugins automatically.

**Comment by cherriesandmochi** [comment] 2024-01-31 10:15
> I expected that obfuscate false would've stopped obfuscation or any resolution here, but I get what you're saying.

I agree, it would make sense for `##OBFUSCATE false` to stop any obfuscation. And a new hint called `##OBFUSCATE_SYMBOL` to skip obfuscation of only declarations.

**Comment by cherriesandmochi** [comment] 2024-02-03 23:06
Yes for sure, the parser I wrote is pretty much just thrown together to at least somewhat work. I do not really have experience with those. Using a 3rd party tool like the GDScript toolkit does seem very tempting.

**Closed as not planned** 2024-02-24 00:16 UTC
Labels: bug, confirmed
